/**
 * Realistic MedSpa mock fixtures for UI development.
 *
 * All timestamps are expressed as relative-to-now ISO strings so fixtures
 * don't go stale as the date changes.
 *
 * TODO: Replace with real Supabase queries once DB tables for contacts,
 * call_summaries, follow_up_tasks, and appointments exist.
 */

import type {
  Contact,
  CallLogEntry,
  CallSummary,
  FollowUpTask,
  Appointment,
  Integration,
  IntegrationSyncLog,
} from '@/lib/types/domain'

// ── Time helpers ──────────────────────────────────────────────────────────────

function hoursAgo(h: number): string {
  return new Date(Date.now() - h * 3600 * 1000).toISOString()
}
function daysAgo(d: number): string {
  return new Date(Date.now() - d * 86400 * 1000).toISOString()
}
function daysFromNow(d: number): string {
  return new Date(Date.now() + d * 86400 * 1000).toISOString()
}
function hoursFromNow(h: number): string {
  return new Date(Date.now() + h * 3600 * 1000).toISOString()
}

// ── Call summaries ────────────────────────────────────────────────────────────

export const MOCK_SUMMARIES: Record<string, CallSummary> = {
  sum_001: {
    id: 'sum_001',
    callLogId: 'call_001',
    tenantId: 'tenant_demo',
    provider: 'retell',
    model: 'gpt-4o',
    plainSummary:
      'Maria called to book a Botox treatment for her forehead lines. She mentioned seeing our Instagram ad. Interested in 20 units. Booked for next Thursday at 2 PM. Price discussed: $400. Very positive about our pricing vs competitors she checked.',
    structuredSummary: {
      intent: 'book_appointment',
      sentiment: 'positive',
      urgency: 'low',
      objections: [],
      outcome: 'booked',
      nextBestAction: 'Send confirmation SMS and pre-care instructions',
      callbackScript: null,
      keyFacts: ['20 units Botox', 'Forehead lines', 'Instagram referral', '$400 agreed'],
      unansweredQuestions: [],
    },
    sentiment: 'positive',
    urgency: 'low',
    createdAt: hoursAgo(22),
  },
  sum_002: {
    id: 'sum_002',
    callLogId: 'call_003',
    tenantId: 'tenant_demo',
    provider: 'retell',
    model: 'gpt-4o',
    plainSummary:
      'Jennifer called about lip filler. Very interested but concerned about looking "overdone." Asked about natural results and recovery time. AI agent could not close — she wants to think about it and will call back. Follow-up recommended within 24h while interest is high.',
    structuredSummary: {
      intent: 'inquiry',
      sentiment: 'neutral',
      urgency: 'high',
      objections: ['Worried about unnatural look', 'Unsure about downtime'],
      outcome: 'follow_up',
      nextBestAction: 'Call back within 24h. Lead showed high intent. Send before/after portfolio.',
      callbackScript:
        `Hi Jennifer, this is [Name] from Luxe Aesthetics. I wanted to follow up on your questions about lip filler. I thought I'd share a few before/after photos that show the subtle, natural look our clients love. Would you have 5 minutes to chat?`,
      keyFacts: ['Lip filler inquiry', 'Natural look concern', 'High intent to book'],
      unansweredQuestions: ['Pricing', 'Availability this week'],
    },
    sentiment: 'neutral',
    urgency: 'high',
    createdAt: hoursAgo(3),
  },
  sum_003: {
    id: 'sum_003',
    callLogId: 'call_007',
    tenantId: 'tenant_demo',
    provider: 'retell',
    model: 'gpt-4o',
    plainSummary:
      'David called to reschedule his no-show from last week. He apologized and mentioned a family emergency. Now wants to rebook CoolSculpting. Rescheduled for Friday 10 AM. Good retention opportunity.',
    structuredSummary: {
      intent: 'reschedule',
      sentiment: 'positive',
      urgency: 'low',
      objections: [],
      outcome: 'booked',
      nextBestAction: 'Send rescheduled confirmation. Consider waiving no-show fee as goodwill gesture.',
      callbackScript: null,
      keyFacts: ['CoolSculpting', 'No-show recovery', 'Family emergency reason'],
      unansweredQuestions: [],
    },
    sentiment: 'positive',
    urgency: 'low',
    createdAt: daysAgo(1),
  },
  sum_004: {
    id: 'sum_004',
    callLogId: 'call_012',
    tenantId: 'tenant_demo',
    provider: 'retell',
    model: 'gpt-4o',
    plainSummary:
      'Sarah called to inquire about laser hair removal pricing for full legs. AI quoted $600/session or $2,800 for 6-session package. She said she found a Groupon deal at a competitor for $199/session and ended the call. Lead marked as lost.',
    structuredSummary: {
      intent: 'inquiry',
      sentiment: 'negative',
      urgency: 'low',
      objections: ['Competitor has Groupon deal at $199/session', 'Price too high'],
      outcome: 'not_interested',
      nextBestAction: 'Add to reactivation list in 60 days. Consider promotional pricing campaign.',
      callbackScript: null,
      keyFacts: ['Full leg laser hair removal', 'Price-sensitive', 'Competitor Groupon'],
      unansweredQuestions: [],
    },
    sentiment: 'negative',
    urgency: 'low',
    createdAt: daysAgo(3),
  },
}

// ── Call log entries ───────────────────────────────────────────────────────────

export const MOCK_CALLS: Record<string, CallLogEntry[]> = {
  contact_001: [
    {
      id: 'call_001',
      tenantId: 'tenant_demo',
      contactId: 'contact_001',
      direction: 'inbound',
      callType: 'booking',
      durationSec: 342,
      outcome: 'booked',
      startedAt: hoursAgo(23),
      endedAt: hoursAgo(22),
      provider: 'retell',
      providerCallId: 'retell_abc001',
      recordingUrl: null,
      transcriptText:
        'Agent: Thank you for calling Luxe Aesthetics, how can I help you today?\nMaria: Hi, I saw your Instagram ad about Botox and I wanted to book an appointment...',
      summaryStatus: 'complete',
      transferToHuman: false,
      agentVersion: 'v2.1',
      summary: MOCK_SUMMARIES['sum_001'],
    },
  ],
  contact_002: [
    {
      id: 'call_003',
      tenantId: 'tenant_demo',
      contactId: 'contact_002',
      direction: 'inbound',
      callType: 'inbound_inquiry',
      durationSec: 198,
      outcome: 'follow_up',
      startedAt: hoursAgo(4),
      endedAt: hoursAgo(3),
      provider: 'retell',
      providerCallId: 'retell_abc003',
      recordingUrl: null,
      transcriptText: null,
      summaryStatus: 'complete',
      transferToHuman: false,
      agentVersion: 'v2.1',
      summary: MOCK_SUMMARIES['sum_002'],
    },
  ],
  contact_003: [
    {
      id: 'call_006',
      tenantId: 'tenant_demo',
      contactId: 'contact_003',
      direction: 'inbound',
      callType: 'booking',
      durationSec: 890,
      outcome: 'no_answer',
      startedAt: daysAgo(8),
      endedAt: daysAgo(8),
      provider: 'retell',
      providerCallId: 'retell_abc006',
      recordingUrl: null,
      transcriptText: null,
      summaryStatus: 'not_applicable',
      transferToHuman: false,
      agentVersion: 'v2.1',
      summary: null,
    },
    {
      id: 'call_007',
      tenantId: 'tenant_demo',
      contactId: 'contact_003',
      direction: 'inbound',
      callType: 'reschedule',
      durationSec: 276,
      outcome: 'booked',
      startedAt: daysAgo(1),
      endedAt: daysAgo(1),
      provider: 'retell',
      providerCallId: 'retell_abc007',
      recordingUrl: null,
      transcriptText: null,
      summaryStatus: 'complete',
      transferToHuman: false,
      agentVersion: 'v2.1',
      summary: MOCK_SUMMARIES['sum_003'],
    },
  ],
  contact_004: [
    {
      id: 'call_012',
      tenantId: 'tenant_demo',
      contactId: 'contact_004',
      direction: 'inbound',
      callType: 'inbound_inquiry',
      durationSec: 124,
      outcome: 'not_interested',
      startedAt: daysAgo(3),
      endedAt: daysAgo(3),
      provider: 'retell',
      providerCallId: 'retell_abc012',
      recordingUrl: null,
      transcriptText: null,
      summaryStatus: 'complete',
      transferToHuman: false,
      agentVersion: 'v2.1',
      summary: MOCK_SUMMARIES['sum_004'],
    },
  ],
  contact_005: [
    {
      id: 'call_015',
      tenantId: 'tenant_demo',
      contactId: 'contact_005',
      direction: 'inbound',
      callType: 'inbound_inquiry',
      durationSec: 87,
      outcome: 'follow_up',
      startedAt: hoursAgo(1),
      endedAt: hoursAgo(1),
      provider: 'retell',
      providerCallId: 'retell_abc015',
      recordingUrl: null,
      transcriptText: null,
      summaryStatus: 'pending',
      transferToHuman: false,
      agentVersion: 'v2.1',
      summary: null,
    },
  ],
  contact_006: [
    {
      id: 'call_020',
      tenantId: 'tenant_demo',
      contactId: 'contact_006',
      direction: 'outbound',
      callType: 'reactivation',
      durationSec: 203,
      outcome: 'interested',
      startedAt: daysAgo(2),
      endedAt: daysAgo(2),
      provider: 'retell',
      providerCallId: 'retell_abc020',
      recordingUrl: null,
      transcriptText: null,
      summaryStatus: 'complete',
      transferToHuman: false,
      agentVersion: 'v2.1',
      summary: null,
    },
  ],
  contact_009: [
    {
      id: 'call_030',
      tenantId: 'tenant_demo',
      contactId: 'contact_009',
      direction: 'inbound',
      callType: 'booking',
      durationSec: 467,
      outcome: 'booked',
      startedAt: hoursAgo(5),
      endedAt: hoursAgo(5),
      provider: 'retell',
      providerCallId: 'retell_abc030',
      recordingUrl: null,
      transcriptText: null,
      summaryStatus: 'complete',
      transferToHuman: false,
      agentVersion: 'v2.1',
      summary: null,
    },
  ],
}

// ── Follow-up tasks ───────────────────────────────────────────────────────────

export const MOCK_TASKS: FollowUpTask[] = [
  {
    id: 'task_001',
    tenantId: 'tenant_demo',
    contactId: 'contact_002',
    taskType: 'callback',
    status: 'open',
    reason: 'High-intent lead interested in lip filler — follow up while interest is hot',
    dueAt: hoursFromNow(2),
    priority: 'high',
    suggestedAction: 'Call Jennifer and send before/after portfolio via SMS',
    suggestedScript:
      `Hi Jennifer, this is [Name] from Luxe Aesthetics. I wanted to follow up on your questions about lip filler. I have some photos of natural results I'd love to share — do you have 5 minutes?`,
    assignedTo: null,
    createdAt: hoursAgo(3),
    updatedAt: hoursAgo(3),
  },
  {
    id: 'task_002',
    tenantId: 'tenant_demo',
    contactId: 'contact_005',
    taskType: 'callback',
    status: 'open',
    reason: 'New lead — summary still processing. Called about chemical peels.',
    dueAt: hoursFromNow(6),
    priority: 'medium',
    suggestedAction: 'Wait for AI summary, then call within 6 hours',
    suggestedScript: null,
    assignedTo: null,
    createdAt: hoursAgo(1),
    updatedAt: hoursAgo(1),
  },
  {
    id: 'task_003',
    tenantId: 'tenant_demo',
    contactId: 'contact_008',
    taskType: 'callback',
    status: 'open',
    reason: 'No answer — 3 attempts. Voicemail left. Try different time of day.',
    dueAt: hoursAgo(1), // OVERDUE
    priority: 'high',
    suggestedAction: 'Try calling after 5 PM — may be working during the day',
    suggestedScript:
      `Hi Robert, this is [Name] from Luxe Aesthetics. I've been trying to reach you about your inquiry. Please call us back or text this number at your convenience.`,
    assignedTo: null,
    createdAt: daysAgo(2),
    updatedAt: daysAgo(1),
  },
  {
    id: 'task_004',
    tenantId: 'tenant_demo',
    contactId: 'contact_006',
    taskType: 'reactivation',
    status: 'in_progress',
    reason: `Client hasn't been in for 7 months — reached via outbound, expressed interest`,
    dueAt: daysFromNow(1),
    priority: 'medium',
    suggestedAction: 'Send personalized offer: 15% off their last service',
    suggestedScript:
      `Hi Ashley, we miss you! As a valued client, we'd love to offer you 15% off your next [service]. Book this week and let us take care of you.`,
    assignedTo: null,
    createdAt: daysAgo(2),
    updatedAt: daysAgo(1),
  },
  {
    id: 'task_005',
    tenantId: 'tenant_demo',
    contactId: 'contact_003',
    taskType: 'reminder',
    status: 'open',
    reason: 'Appointment tomorrow — send reminder to prevent no-show (previous no-show on record)',
    dueAt: hoursFromNow(4),
    priority: 'high',
    suggestedAction: 'Send reminder SMS with prep instructions',
    suggestedScript:
      'Hi David, just a reminder that your CoolSculpting appointment is tomorrow at 10 AM. Please arrive 10 minutes early. Reply CONFIRM to confirm or RESCHEDULE if you need to change.',
    assignedTo: null,
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
  },
  {
    id: 'task_006',
    tenantId: 'tenant_demo',
    contactId: 'contact_007',
    taskType: 'human_review',
    status: 'open',
    reason: 'Call transferred to human — patient mentioned allergy concern. Requires clinical review.',
    dueAt: hoursAgo(3), // OVERDUE
    priority: 'high',
    suggestedAction: 'Clinical staff to review allergy concern before confirming appointment',
    suggestedScript: null,
    assignedTo: null,
    createdAt: hoursAgo(5),
    updatedAt: hoursAgo(5),
  },
]

// ── Appointments ──────────────────────────────────────────────────────────────

export const MOCK_APPOINTMENTS: Appointment[] = [
  {
    id: 'appt_001',
    tenantId: 'tenant_demo',
    contactId: 'contact_001',
    externalId: null,
    status: 'confirmed',
    startAt: daysFromNow(4),
    endAt: null,
    serviceName: 'Botox — Forehead (20 units)',
    providerName: 'Dr. Karen Mills',
    valueEstimate: 400,
  },
  {
    id: 'appt_002',
    tenantId: 'tenant_demo',
    contactId: 'contact_003',
    externalId: null,
    status: 'booked',
    startAt: daysFromNow(1),
    endAt: null,
    serviceName: 'CoolSculpting — Abdomen',
    providerName: 'Lisa Chen, LPN',
    valueEstimate: 1200,
  },
  {
    id: 'appt_003',
    tenantId: 'tenant_demo',
    contactId: 'contact_007',
    externalId: null,
    status: 'booked',
    startAt: daysFromNow(3),
    endAt: null,
    serviceName: 'Chemical Peel — Medium',
    providerName: 'Dr. Karen Mills',
    valueEstimate: 350,
  },
  {
    id: 'appt_004',
    tenantId: 'tenant_demo',
    contactId: 'contact_009',
    externalId: null,
    status: 'booked',
    startAt: daysFromNow(6),
    endAt: null,
    serviceName: 'Full Facial Rejuvenation Package',
    providerName: 'Lisa Chen, LPN',
    valueEstimate: 2800,
  },
]

// ── Contacts (leads) ──────────────────────────────────────────────────────────

export const MOCK_CONTACTS: Contact[] = [
  {
    id: 'contact_001',
    tenantId: 'tenant_demo',
    fullName: 'Maria Rodriguez',
    phone: '+1 (305) 555-0142',
    email: 'maria.r@email.com',
    tags: ['instagram-ad', 'botox', 'new-client'],
    source: 'instagram',
    status: 'booked',
    ownerType: 'ai',
    priorityScore: 92,
    lastCallAt: hoursAgo(23),
    nextActionAt: null,
    createdAt: hoursAgo(24),
    updatedAt: hoursAgo(22),
    latestCallSummary: MOCK_SUMMARIES['sum_001'],
    openFollowUpTasks: [],
    recentCalls: MOCK_CALLS['contact_001'],
    appointments: [MOCK_APPOINTMENTS[0]],
  },
  {
    id: 'contact_002',
    tenantId: 'tenant_demo',
    fullName: 'Jennifer Smith',
    phone: '+1 (786) 555-0388',
    email: null,
    tags: ['lip-filler', 'high-intent', 'price-ok'],
    source: 'google',
    status: 'interested',
    ownerType: 'human',
    priorityScore: 88,
    lastCallAt: hoursAgo(4),
    nextActionAt: hoursFromNow(2),
    createdAt: hoursAgo(4),
    updatedAt: hoursAgo(3),
    latestCallSummary: MOCK_SUMMARIES['sum_002'],
    openFollowUpTasks: [MOCK_TASKS[0]],
    recentCalls: MOCK_CALLS['contact_002'],
    appointments: [],
  },
  {
    id: 'contact_003',
    tenantId: 'tenant_demo',
    fullName: 'David Kim',
    phone: '+1 (954) 555-0271',
    email: 'david.kim@gmail.com',
    tags: ['coolsculpting', 'no-show-history', 'rescheduled'],
    source: 'referral',
    status: 'booked',
    ownerType: 'ai',
    priorityScore: 75,
    lastCallAt: daysAgo(1),
    nextActionAt: hoursFromNow(4),
    createdAt: daysAgo(8),
    updatedAt: daysAgo(1),
    latestCallSummary: MOCK_SUMMARIES['sum_003'],
    openFollowUpTasks: [MOCK_TASKS[4]],
    recentCalls: MOCK_CALLS['contact_003'],
    appointments: [MOCK_APPOINTMENTS[1]],
  },
  {
    id: 'contact_004',
    tenantId: 'tenant_demo',
    fullName: 'Sarah Johnson',
    phone: '+1 (561) 555-0044',
    email: 'sarah.j@outlook.com',
    tags: ['laser-hair', 'price-sensitive', 'competitor-loss'],
    source: 'phone',
    status: 'lost',
    ownerType: 'ai',
    priorityScore: 18,
    lastCallAt: daysAgo(3),
    nextActionAt: null,
    createdAt: daysAgo(3),
    updatedAt: daysAgo(3),
    latestCallSummary: MOCK_SUMMARIES['sum_004'],
    openFollowUpTasks: [],
    recentCalls: MOCK_CALLS['contact_004'],
    appointments: [],
  },
  {
    id: 'contact_005',
    tenantId: 'tenant_demo',
    fullName: 'Michael Chen',
    phone: '+1 (407) 555-0193',
    email: null,
    tags: ['chemical-peel', 'new-lead'],
    source: 'website',
    status: 'new',
    ownerType: 'ai',
    priorityScore: 61,
    lastCallAt: hoursAgo(1),
    nextActionAt: hoursFromNow(6),
    createdAt: hoursAgo(1),
    updatedAt: hoursAgo(1),
    latestCallSummary: null,
    openFollowUpTasks: [MOCK_TASKS[1]],
    recentCalls: MOCK_CALLS['contact_005'],
    appointments: [],
  },
  {
    id: 'contact_006',
    tenantId: 'tenant_demo',
    fullName: 'Ashley Williams',
    phone: '+1 (305) 555-0517',
    email: 'ashley.w@gmail.com',
    tags: ['reactivation', 'lapsed-7m', 'vip'],
    source: 'phone',
    status: 'reactivation',
    ownerType: 'ai',
    priorityScore: 70,
    lastCallAt: daysAgo(2),
    nextActionAt: daysFromNow(1),
    createdAt: daysAgo(210),
    updatedAt: daysAgo(2),
    latestCallSummary: null,
    openFollowUpTasks: [MOCK_TASKS[3]],
    recentCalls: MOCK_CALLS['contact_006'],
    appointments: [],
  },
  {
    id: 'contact_007',
    tenantId: 'tenant_demo',
    fullName: 'Emily Davis',
    phone: '+1 (786) 555-0722',
    email: 'emily.davis@work.com',
    tags: ['chemical-peel', 'allergy-concern', 'transfer-to-human'],
    source: 'google',
    status: 'booked',
    ownerType: 'human',
    priorityScore: 83,
    lastCallAt: hoursAgo(5),
    nextActionAt: hoursAgo(3),
    createdAt: hoursAgo(5),
    updatedAt: hoursAgo(5),
    latestCallSummary: null,
    openFollowUpTasks: [MOCK_TASKS[5]],
    recentCalls: [],
    appointments: [MOCK_APPOINTMENTS[2]],
  },
  {
    id: 'contact_008',
    tenantId: 'tenant_demo',
    fullName: 'Robert Martinez',
    phone: '+1 (954) 555-0833',
    email: null,
    tags: ['no-answer', 'voicemail-x3'],
    source: 'website',
    status: 'contacted',
    ownerType: 'ai',
    priorityScore: 45,
    lastCallAt: daysAgo(2),
    nextActionAt: hoursAgo(1),
    createdAt: daysAgo(3),
    updatedAt: daysAgo(1),
    latestCallSummary: null,
    openFollowUpTasks: [MOCK_TASKS[2]],
    recentCalls: [],
    appointments: [],
  },
  {
    id: 'contact_009',
    tenantId: 'tenant_demo',
    fullName: 'Jessica Brown',
    phone: '+1 (305) 555-0966',
    email: 'jessica.b@email.com',
    tags: ['facial-package', 'premium', 'vip', 'high-value'],
    source: 'referral',
    status: 'booked',
    ownerType: 'ai',
    priorityScore: 97,
    lastCallAt: hoursAgo(5),
    nextActionAt: null,
    createdAt: daysAgo(1),
    updatedAt: hoursAgo(5),
    latestCallSummary: null,
    openFollowUpTasks: [],
    recentCalls: MOCK_CALLS['contact_009'],
    appointments: [MOCK_APPOINTMENTS[3]],
  },
  {
    id: 'contact_010',
    tenantId: 'tenant_demo',
    fullName: 'Thomas Wilson',
    phone: '+1 (561) 555-0001',
    email: null,
    tags: ['spam', 'wrong-number'],
    source: 'phone',
    status: 'lost',
    ownerType: 'ai',
    priorityScore: 0,
    lastCallAt: daysAgo(5),
    nextActionAt: null,
    createdAt: daysAgo(5),
    updatedAt: daysAgo(5),
    latestCallSummary: null,
    openFollowUpTasks: [],
    recentCalls: [],
    appointments: [],
  },
]

// ── Integrations ──────────────────────────────────────────────────────────────

export const MOCK_INTEGRATIONS: Integration[] = [
  {
    id: 'int_001',
    tenantId: 'tenant_demo',
    provider: 'custom_webhook',
    status: 'active',
    configJson: {
      webhookUrl: 'https://n8n.yourdomain.com/webhook/servify-events',
      secret: '••••••••••••',
      events: ['lead.created', 'call.completed', 'summary.created', 'booking.created'],
    },
    lastSyncedAt: hoursAgo(1),
    lastError: null,
    createdAt: daysAgo(30),
    updatedAt: hoursAgo(1),
  },
]

export const MOCK_SYNC_LOGS: IntegrationSyncLog[] = [
  {
    id: 'sync_001',
    tenantId: 'tenant_demo',
    integrationId: 'int_001',
    direction: 'outbound',
    eventType: 'booking.created',
    status: 'success',
    payloadJson: { contactId: 'contact_001', event: 'booking.created' },
    responseJson: { status: 200, message: 'OK' },
    error: null,
    createdAt: hoursAgo(1),
  },
  {
    id: 'sync_002',
    tenantId: 'tenant_demo',
    integrationId: 'int_001',
    direction: 'outbound',
    eventType: 'call.completed',
    status: 'success',
    payloadJson: { contactId: 'contact_002', event: 'call.completed' },
    responseJson: { status: 200, message: 'OK' },
    error: null,
    createdAt: hoursAgo(4),
  },
  {
    id: 'sync_003',
    tenantId: 'tenant_demo',
    integrationId: 'int_001',
    direction: 'outbound',
    eventType: 'lead.created',
    status: 'failed',
    payloadJson: { contactId: 'contact_005', event: 'lead.created' },
    responseJson: null,
    error: 'Connection timeout after 5s',
    createdAt: hoursAgo(1),
  },
  {
    id: 'sync_004',
    tenantId: 'tenant_demo',
    integrationId: 'int_001',
    direction: 'outbound',
    eventType: 'summary.created',
    status: 'success',
    payloadJson: { contactId: 'contact_001', event: 'summary.created' },
    responseJson: { status: 200, message: 'OK' },
    error: null,
    createdAt: hoursAgo(22),
  },
  {
    id: 'sync_005',
    tenantId: 'tenant_demo',
    integrationId: 'int_001',
    direction: 'outbound',
    eventType: 'call.completed',
    status: 'success',
    payloadJson: { contactId: 'contact_003', event: 'call.completed' },
    responseJson: { status: 200, message: 'OK' },
    error: null,
    createdAt: daysAgo(1),
  },
]

// ── Accessor helpers ──────────────────────────────────────────────────────────

/** Returns all contacts for a given tenant (mock — ignores tenantId for now) */
export function getMockContacts(_tenantId: string): Contact[] {
  return MOCK_CONTACTS
}

/** Returns all open follow-up tasks for a given tenant */
export function getMockFollowUpTasks(_tenantId: string): FollowUpTask[] {
  const contacts = MOCK_CONTACTS.reduce<Record<string, Contact>>((acc, c) => {
    acc[c.id] = c
    return acc
  }, {})

  return MOCK_TASKS.map((task) => ({
    ...task,
    contact: contacts[task.contactId],
  }))
}

/** Returns integrations for a given tenant */
export function getMockIntegrations(_tenantId: string): Integration[] {
  return MOCK_INTEGRATIONS
}

/** Returns sync logs for a given integration */
export function getMockSyncLogs(integrationId: string): IntegrationSyncLog[] {
  return MOCK_SYNC_LOGS.filter((l) => l.integrationId === integrationId)
}
