/**
 * Report Export — text formatting + clipboard helpers.
 *
 * Pure functions that format ROI and executive data into structured
 * text suitable for clipboard, email body, or API payload preview.
 */

import type { RoiSummary, MissedCallRecoveryResult } from './roi-proof'
import type { ConversionFunnel } from './conversion-metrics'

// ── Types ────────────────────────────────────────────────────────────────────

export interface ReportPayload {
  tenantName: string
  periodLabel: string
  roi: RoiSummary
  recovery: MissedCallRecoveryResult
  funnel: ConversionFunnel
  currency: string
  generatedAt: string
}

// ── Text formatter ───────────────────────────────────────────────────────────

function fmt(amount: number, currency: string): string {
  return new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency,
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(amount)
}

/**
 * Format a full executive report as structured plain text.
 */
export function formatReportAsText(payload: ReportPayload): string {
  const { tenantName, periodLabel, roi, recovery, funnel, currency } = payload

  const lines = [
    `AI Receptionist — Monthly Executive Report`,
    tenantName,
    periodLabel,
    '',
    '━━━ PERFORMANCE SUMMARY ━━━',
    '',
    `Calls Handled:          ${roi.totalCalls}`,
    `Appointments Booked:    ${roi.totalBooked}`,
    `Lead Conversion Rate:   ${roi.conversionRate}%`,
    '',
    '━━━ REVENUE IMPACT ━━━',
    '',
    `Booked Revenue:         ${fmt(roi.bookedRevenue, currency)} (reported)`,
    `Labor Cost Savings:     ${fmt(roi.laborSavings, currency)} (${roi.hoursSaved}h saved, estimated)`,
    `Recovered Revenue:      ${fmt(roi.recoveredRevenue, currency)} (${recovery.recoveredCalls.length} missed calls recovered, estimated)`,
    '',
    `Total Value Generated:  ${fmt(roi.totalValueGenerated, currency)}`,
    `Subscription Cost:      ${fmt(roi.subscriptionCost, currency)}/mo`,
    roi.roiPercent !== null
      ? `Net ROI:                ${roi.roiPercent > 0 ? '+' : ''}${roi.roiPercent}%`
      : '',
    '',
    '━━━ CONVERSION FUNNEL ━━━',
    '',
    ...funnel.steps.map(
      (s) =>
        `${s.label.padEnd(20)} ${String(s.count).padStart(5)}${s.rateFromPrev !== null ? `  (${s.rateFromPrev}% from prev)` : ''}`,
    ),
    '',
    '━━━ MISSED CALL RECOVERY ━━━',
    '',
    `Total Missed:           ${recovery.totalMissed}`,
    `Recovered:              ${recovery.recoveredCalls.length}`,
    `Recovery Rate:          ${recovery.recoveryRate}%`,
    `Revenue Recovered:      ${fmt(recovery.totalRecoveredRevenue, currency)}`,
    '',
    '—',
    'Generated by Servify AI Receptionist Dashboard',
    `Report date: ${payload.generatedAt}`,
  ].filter((line) => line !== undefined)

  return lines.join('\n')
}

/**
 * Build a serializable report payload from computed data.
 */
export function buildReportPayload(opts: {
  tenantName: string
  roi: RoiSummary
  recovery: MissedCallRecoveryResult
  funnel: ConversionFunnel
  currency: string
}): ReportPayload {
  const end = new Date()
  const start = new Date(Date.now() - 30 * 86_400_000)
  const periodLabel = `${start.toLocaleDateString('en', { month: 'long', day: 'numeric' })} – ${end.toLocaleDateString('en', { month: 'long', day: 'numeric', year: 'numeric' })}`

  return {
    tenantName: opts.tenantName,
    periodLabel,
    roi: opts.roi,
    recovery: opts.recovery,
    funnel: opts.funnel,
    currency: opts.currency,
    generatedAt: end.toISOString(),
  }
}

// ── Clipboard helper ─────────────────────────────────────────────────────────

/**
 * Copy text to clipboard with fallback for older browsers.
 * Returns true on success, false on failure.
 */
export async function copyToClipboard(text: string): Promise<boolean> {
  // Modern API
  if (navigator.clipboard?.writeText) {
    try {
      await navigator.clipboard.writeText(text)
      return true
    } catch {
      // Fall through to fallback
    }
  }

  // Fallback: hidden textarea
  try {
    const textarea = document.createElement('textarea')
    textarea.value = text
    textarea.style.cssText = 'position:fixed;opacity:0;pointer-events:none;'
    document.body.appendChild(textarea)
    textarea.select()
    const ok = document.execCommand('copy')
    document.body.removeChild(textarea)
    return ok
  } catch {
    return false
  }
}
